const express = require('express');
const router = express.Router();
const passport = require('passport');

const { strategy } = require('./app/controller/mainTask/passport');
passport.use(strategy);

const mainController = require('./app/controller/mainTask/controller');
const taskController = require('./app/controller/Task1-9/controller');
const task10Controller = require('./app/controller/Task10/controller');
const dbController = require('./app/controller/Task10/dbController');
const task11Controller = require('./app/controller/Task11/controller');
const task12Controller = require('./app/controller/Task12/controller');
const htmlTaskController= require('./app/controller/htmlTask/controller');

router.get('/',mainController.getRegister);
router.post('/',mainController.postRegister);
router.get('/AccountActivation/:code',mainController.getAccountActivationCode);
router.post('/AccountActivation/:code',mainController.postAccountActivationCode);
router.get('/login',mainController.getLogin);
router.post('/login',mainController.postlogin);
router.get('/taskList',passport.authenticate('jwt', { session: false }),mainController.getTaskList);
router.get('/task1',passport.authenticate('jwt', { session: false }),taskController.getTask1);
router.get('/task2',passport.authenticate('jwt', { session: false }),taskController.getTask2);
router.get('/task3',passport.authenticate('jwt', { session: false }),taskController.getTask3);
router.get('/task4',passport.authenticate('jwt', { session: false }),taskController.getTask4);
router.get('/task5',passport.authenticate('jwt', { session: false }),taskController.getTask5);
router.get('/task6',passport.authenticate('jwt', { session: false }),taskController.getTask6);
router.get('/task6/:id',passport.authenticate('jwt', { session: false }),taskController.getTask6Id);
router.get('/task7',passport.authenticate('jwt', { session: false }),taskController.getTask7);
router.get('/task7/:col/:id',passport.authenticate('jwt', { session: false }),taskController.getTask7Id);
router.get('/task8/:id/:search',passport.authenticate('jwt', { session: false }),taskController.getTask8);
router.get('/task9',passport.authenticate('jwt', { session: false }),taskController.getTask9);
router.post('/task9',passport.authenticate('jwt', { session: false }),taskController.postTask9);
router.get('/task10',passport.authenticate('jwt', { session: false }),task10Controller.getTask10);
router.get('/task10/:id',passport.authenticate('jwt', { session: false }),task10Controller.getTask10);
router.post('/task10/:id',passport.authenticate('jwt', { session: false }),task10Controller.postTask10Id);
router.post('/task10',passport.authenticate('jwt', { session: false }),task10Controller.postTask10);
router.get('/db-Candidatemaster/:id',passport.authenticate('jwt',{session:false}),dbController.getCandidatemaster);
router.get('/db-Candidatemaster',passport.authenticate('jwt',{session:false}),dbController.getCandidatemasterAll);
router.get('/db-EducationDetails/:id',passport.authenticate('jwt',{session:false}),dbController.getEducationDetails);
router.get('/db-WorkExprience/:id',passport.authenticate('jwt',{session:false}),dbController.getWorkExprience);
router.get('/db-LanguageTable/:id',passport.authenticate('jwt',{session:false}),dbController.getLanguageTable);
router.get('/db-TechnologiesTable/:id',passport.authenticate('jwt',{session:false}),dbController.getTechnologiesTable);
router.get('/db-ReferanceContact/:id',passport.authenticate('jwt',{session:false}),dbController.getReferanceTable);
router.get('/db-Perferances/:id',passport.authenticate('jwt',{session:false}),dbController.getPerferances);
router.get('/resultTable',passport.authenticate('jwt',{session:false}),task11Controller.getResultTable);
router.get('/resultTable/:id',passport.authenticate('jwt',{session:false}),task11Controller.getResultTableParm);
router.get('/result',passport.authenticate('jwt',{session:false}),task11Controller.getResult);
router.get('/result/:colName/:page',passport.authenticate('jwt',{session:false}),task11Controller.getResultParm);
router.get('/Task12',passport.authenticate('jwt',{session:false}),task12Controller.getDisplayRedirect);
router.get('/Task12/add',passport.authenticate('jwt',{session:false}),task12Controller.getTask12Add);
router.post('/Task12',passport.authenticate('jwt',{session:false}),task12Controller.postTask12);
router.get('/Task12/display',passport.authenticate('jwt',{session:false}),task12Controller.getDisplay);
router.get('/Task12/update/:id',passport.authenticate('jwt',{session:false}),task12Controller.getUpdateParm);
router.post('/Task12/update/:id',passport.authenticate('jwt',{session:false}),task12Controller.postUpdateParm);
router.get('/htmlTask1',passport.authenticate('jwt',{session:false}),htmlTaskController.getHtmlTask1);
router.get('/htmlTask2',passport.authenticate('jwt',{session:false}),htmlTaskController.getHtmlTask2);
router.get('/htmlTask3',passport.authenticate('jwt',{session:false}),htmlTaskController.getHtmlTask3);

module.exports = router;